# Drift-aware algorithm and product version
version: v100

# Data repositories
dir:
  cryosat2:
    level2:
      sea_ice_freeboard: "/Volumes/data2/projects/chione/data/cryosat2/l2p_cci/"
      sea_ice_thickness: "/Volumes/data2/projects/chione/data/cryosat2/l2p_cci/"
    geojson: "/Volumes/data2/projects/chione/product/cryosat2/geojson_ex/"
    netcdf: "/Volumes/data2/projects/chione/product/cryosat2/netcdf_ex2/"
    visu: "/Volumes/data2/projects/chione/analysis/cryosat2/plots/"
  envisat:
    level2:
      sea_ice_freeboard: "/Volumes/data2/projects/chione/data/envisat/l2p_cci/"
      sea_ice_thickness: "/Volumes/data2/projects/chione/data/envisat/l2p_cci/"
    geojson: "/Volumes/data2/projects/chione/product/envisat/geojson/"
    netcdf: "/Volumes/data2/projects/chione/product/envisat/netcdf/"
    visu: "/Volumes/data2/projects/chione/analysis/envisat/plots/"
  icesat2:
    level2:
      total_freeboard: "/Volumes/data2/projects/chione/data/icesat2/ATL10.005/"
      sea_ice_thickness: "/Volumes/data2/projects/chione/data/icesat2/is2sitdata/"
    geojson: "/Volumes/data2/projects/chione/product/icesat2/geojson/"
    netcdf: "/Volumes/data2/projects/chione/product/icesat2/netcdf/"
    visu: "/Volumes/data2/projects/chione/analysis/icesat2/plots/"
  auxiliary:
    ice_conc:
      osi450: "/Volumes/data2/projects/chione/auxiliary/OSI450/" #v3.0: 1978-2020
      osi430b: "/Volumes/data2/projects/chione/auxiliary/OSI430b/" #v3.0: 2021-
    ice_drift:
      osi455: "/Volumes/data2/projects/chione/auxiliary/OSI455/" #1991-2020
      osi405: "/Volumes/data2/projects/chione/auxiliary/OSI405/" #2009-
    reg_mask: "/Volumes/data2/projects/chione/auxiliary/arctic_regions/NSIDC-0780_SeaIceRegions_EASE2-N12.5km_v1.0.nc"
  logging: "/Volumes/data2/projects/chione/logging/"


# User settings
user:
  name: rricker

# Processing options
options:
  proc_step: stacking # Available options: stacking, gridding, and visualization
  sensor: icesat2 # Available options: envisat, cryosat2 and icesat2
  ice_conc_product: osi430b
  ice_drift_product: osi405
  target_variable: 'sea_ice_thickness' # Available options: sea_ice_freeboard (cryosat2), total_freeboard (icesat2), and sea_ice_thickness (cryosat2, icesat2)
  add_variable: ['snow_depth']
  target_variable_range:
    freeboard: [ 0, 2 ]
    thickness: [ 0, 20 ]
  hemisphere: nh # Available options: nh
  out_epsg: 'EPSG:6931' # EASE2: 'EPSG:6931', NSIDC Polar-Stereo: 'EPSG:3411'

  # Processing options for each processing step
  proc_step_options:
    # Processing step: stacking
    stacking:
      mode: fr # f: only forward, r: only reverse, fr: forward and reverse merged (symmetric stack)
      t_start: 2021-10-01 00:00:00
      t_length: 212
      t_window: 16
      multiproc: true
      parcel_grid:
        bounds: [-5400000, -5400000, 5400000, 5400000]
        dim: 1080
      hist:
        n_bins: 40
        range:
          freeboard: [0, 1]
          thickness: [0, 10]
      growth_estimation:
        growth_grid:
          bounds: [ -5400000, -5400000, 5400000, 5400000 ]
          dim: 432
        min_n_tiepoints: 3
        growth_range:
          freeboard: [ -0.25, 0.25 ]
          thickness: [ -2.5, 2.5 ]

    # Processing step: gridding
    gridding:
      sub_dir: test123
      mode: drift-aware
      multiproc: False
      netcdf_grid:
        bounds: [-5400000, -5400000, 5400000, 5400000]
        dim: 432

    # Processing step: visualization
    visualization:
      variable: sea_ice_thickness
      make_gif: True
