base_dir: "/cluster/work/users/rori" # project directory
#-----------------------------------DATA REPOSITORY---------------------------------------------------------------------
input_dir: # relative to base_dir
  envisat: "input_data/envisat/l2p_cci/"
  cryosat2: "input_data/cryosat2/l2p_cci/"
  sentinel3a: "input_data/sentinel3a/l2p_cci"
  sentinel3b: "input_data/sentinel3b/l2p_cci"
  icesat2:
    total_freeboard: "input_data/icesat2/ATL10.005"
    sea_ice_thickness: "input_data/icesat2/is2sitdata"
#-----------------------------------PRODUCT REPOSITORY------------------------------------------------------------------
output_dir: # relative to base_dir
  trajectories: "product/{sensor}/csv"  # DA trajectories as daily CSVs
  gridded_data: "product/{sensor}/netcdf"  # Gridded DA data as daily NetCDFs
#-----------------------------------AUXILIARY DATA REPOSITORY-----------------------------------------------------------
auxiliary:
  ice_conc:
    osi450: "auxiliary/osi450" #v3.0: 1978-2020
    osi430b: "auxiliary/osi430b" #v3.0: 2021-
  ice_drift:
    osi455: "auxiliary/osi455" #1991-2020
    osi405: "auxiliary/osi405" #2009-
  reg_mask: "auxiliary/arctic_regions/NSIDC-0780_SeaIceRegions_EASE2-N12.5km_v1.0.nc"
#-----------------------------------VISUALIZATION-----------------------------------------------------------------------
visualization: "visualization/plots"
#-----------------------------------LOGGING-----------------------------------------------------------------------------
logging: "logging"
#-----------------------------------PROCESSING OPTIONS BLOCK------------------------------------------------------------
options:
  sensor: sentinel3a # Available options: envisat, cryosat2, sentinel3a, sentinel3b, icesat2
  proc_step: gridding # Available options: stacking, gridding, and visualization
  ice_conc_product: osi450
  ice_drift_product: osi455
  target_variable: 'sea_ice_thickness'                        # Available options: sea_ice_freeboard (radar altimeters),
                                                              # total_freeboard (icesat2), and sea_ice_thickness (all)
  add_variable: ['snow_depth']                                # add variables to the trajectory data frame,
                                                              # no growth correction, no histogram
  hemisphere: sh                                              # Available options: nh, sh
  out_epsg: 'EPSG:6932'                                       # EASE2 NORTH: 'EPSG:6931', EASE2 SOUTH: 'EPSG:6932'

  proc_step_options:                                          # Processing options for each processing step

    stacking:                                                 # Processing step: stacking (Drift-Aware processing)
      filename_prefix: 'ESACCI-SEAICE'                        # project name (e.g., SOSIMBA)
      mode: fr # f: only forward, r: only reverse, fr: forward and reverse merged (symmetric stack)
      t_start: 2019-08-01 00:00:00                            # Start of processing period
      t_length: season                                        # length of processing period in days
      t_window: 16                                            # length of the drift-aware window in days
      multiproc: False                                        # Parallel processing
      num_cpus: 16                                            # Number of CPUs for parallel processing
      parcel_grid:
        bounds: [-5400000, -5400000, 5400000, 5400000]
        dim: 1080
      hist:
        n_bins: 40                                            # number of histogram bins
        range:
          freeboard: [0, 1]                                   # freeboard hist range min/max (m)
          thickness: [0, 10]                                  # thickness hist range min/max (m)
      growth_estimation:
        growth_grid:
          bounds: [ -5400000, -5400000, 5400000, 5400000 ]
          dim: 432
        min_n_tiepoints: 3                                    # min number of tie points for the linear growth fitting
        growth_range:
          freeboard: [ -0.25, 0.25 ] # min/max limits for freeboard growth, neglected if outside
          thickness: [ -2.5, 2.5 ]   # min/max limits for thickness growth, neglected if outside

    gridding:                                                 # Processing step: gridding
      csv_dir: 'sea_ice_thickness-sh-10fr-epsg6932_141-2024-12-16_10-24-43'
      mode: 'da'                                             # drift-aware: da, conventional: cv
      multiproc: False                                       # Parallel processing
      num_cpus: 16                                           # Number of CPUs for parallel processing
      organize_files: True                                   # Organize files in year/month
      netcdf_grid:
        bounds: [-5400000, -5400000, 5400000, 5400000]
        dim: 432
      target_variable_range:
        freeboard: [ 0, 1 ]
        thickness: [ 0, 10 ]

    visualization:                                            # Processing step: visualization
      gridded_data_dir: 'crdp_figs'                           # directory relative to output_dir.gridded_data
      variable: "sea_ice_thickness_growth_interpolated"       # netcdf variable
      make_gif: False

version: 100                                                  # version of DA-SIT python software