variables:
  da: # drift-aware
    histogram: True
    include:
      - "{{ target_var }}"
      - "{{ target_var }}_l2_unc"
      #- "{{ target_var }}_drift_unc"
      - "{{ target_var }}_growth_unc"
      - "{{ target_var }}_total_unc"
      #- "{{ target_var }}_mode"
      #- "{{ target_var }}_uncorrected"
      - "growth"
      - "growth_interpolated"
      - "dist_acquisition"
      - "dt_days"
      - "ice_conc"
      #- "deformation"
      #- "shear"
      #- "divergence"
      - "snow_depth"
      - "drift_unc"
    rename:
      - "{{ target_var }}"
      - "{{ target_var }}_l2_unc"
      #- "{{ target_var }}_drift_unc"
      - "{{ target_var }}_growth_unc"
      - "{{ target_var }}_total_unc"
      #- "{{ target_var }}_mode"
      #- "{{ target_var }}_uncorrected"
      - "{{ target_var }}_growth"
      - "{{ target_var }}_growth_interpolated"
      - "dist_acquisition"
      - "time_offset_acquisition"
      - "sea_ice_concentration"
      #- "deformation"
      #- "shear"
      #- "divergence"
      - "snow_depth"
      - "drift_unc"

  cv: # conventional
    histogram: True
    include:
      - "{{ target_var }}"
      - "{{ target_var }}_l2_unc"
      - "{{ target_var }}_mode"
      - "dist_acquisition"
      - "dt_days"
      - "ice_conc"
      - "deformation"
      - "shear"
      - "divergence"
      - "snow_depth"
    rename:
      - "{{ target_var }}"
      - "{{ target_var }}_l2_unc"
      - "{{ target_var }}_mode"
      - "dist_acquisition"
      - "time_offset_acquisition"
      - "sea_ice_concentration"
      - "deformation"
      - "shear"
      - "divergence"
      - "snow_depth"

variable_attributes:
  xc:
    standard_name: "projection_x_coordinate"
    long_name: "x coordinate of projection (eastings)"
    units: "m"

  yc:
    standard_name: "projection_y_coordinate"
    long_name: "y coordinate of projection (northings)"
    units: "m"

  hist_bins:
    standard_name: "bin_centers"
    long_name: "histogram bin centers"
    units: "m"

  latitude:
    standard_name: "latitude"
    long_name: "latitude of grid cell center"
    units: "degrees_north"

  longitude:
    standard_name: "longitude"
    long_name: "time longitude of grid cell center"
    units: "degrees_east"

  sea_ice_concentration:
    standard_name: 'sea_ice_area_fraction'
    long_name: "sea ice concentration"
    coordinates: "time longitude latitude"
    units: "percent"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness:
    standard_name: 'sea_ice_thickness'
    long_name: "sea ice thickness"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_std:
    standard_name: 'sea_ice_thickness'
    long_name: "standard deviation of sea ice thickness estimates within parcel"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_mode:
    standard_name: 'sea_ice_thickness'
    long_name: "modal sea ice thickness"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_hist:
    standard_name: 'sea_ice_thickness'
    long_name: "thickness classes between 0 m and 10 m with 0.25m bin size"
    coordinates: "time longitude latitude"
    units: "1"
    grid_mapping: 'crs'
    comment: "grid cells contain the absolute counts for each bin"

  sea_ice_thickness_growth:
    standard_name: 'sea_ice_thickness_change'
    long_name: "sea ice thickness growth: rate of change in sea ice thickness per day"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_growth_interpolated:
    standard_name: 'sea_ice_thickness_change'
    long_name: "interpolated sea ice thickness growth"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_drift_unc:
    standard_name: 'sea_ice_thickness standard_error'
    long_name: "sea ice thickness uncertainty associated with the ice drift correction"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_growth_unc:
    standard_name: 'sea_ice_thickness_change standard_error'
    long_name: "sea ice thickness uncertainty associated with the sea ice thickness growth per day"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_l2_unc:
    standard_name: 'sea_ice_thickness standard_error'
    long_name: "sea ice thickness uncertainty associated with the level2 product"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  sea_ice_thickness_total_unc:
    standard_name: 'sea_ice_thickness standard_error'
    long_name: "combined sea ice thickness uncertainty"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  snow_depth:
    standard_name: 'surface_snow_thickness_where_sea_ice'
    long_name: "thickness of the snow layer"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  drift_unc:
    standard_name: 'sea_ice_displacement standard_error'
    long_name: "uncertainty of the accumulated sea ice displacement"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  deformation:
    standard_name: 'deformation'
    long_name: "mean deformation accumulated along the trajectory"
    coordinates: "time longitude latitude"
    units: "1/day"
    grid_mapping: 'crs'
    comment: ""

  divergence:
    standard_name: 'divergence'
    long_name: "mean divergence accumulated along the trajectory"
    coordinates: "time longitude latitude"
    units: "1/day"
    grid_mapping: 'crs'
    comment: ""

  shear:
    standard_name: 'shear'
    long_name: "mean shear accumulated along the trajectory"
    coordinates: "time longitude latitude"
    units: "1/day"
    grid_mapping: 'crs'
    comment: ""

  dist_acquisition:
    standard_name: 'geospatial_distance'
    long_name: "distance between target day and day of data acquisition location"
    coordinates: "time longitude latitude"
    units: "m"
    grid_mapping: 'crs'
    comment: ""

  time:
    standard_name: 'time'
    long_name: 'Time'
    axis: "T"
    bounds: "time_bnds"
    calendar: "standard"
    units: 'seconds since 1970-01-01 00:00:00'

  time_bnds:
    long_name: "Time Bounds"
    units: 'seconds since 1970-01-01 00:00:00'

  time_offset_acquisition:
    standard_name: 'delta_time'
    long_name: "time since data acquisition"
    coordinates: "time longitude latitude"
    units: "days"
    grid_mapping: 'crs'
    comment: ""
